package com.thalesgroup.dtwc.protege;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: RuntimeEvidence <br>
 * @version generated on Wed Oct 08 11:02:03 CEST 2014 by t0013577
 */

public interface RuntimeEvidence extends Evidence {

    /* ***************************************************
     * Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasMetric
     */
     
    /**
     * Gets all property values for the hasMetric property.<p>
     * 
     * @returns a collection of values for the hasMetric property.
     */
    Collection<? extends WrappedIndividual> getHasMetric();

    /**
     * Checks if the class has a hasMetric property value.<p>
     * 
     * @return true if there is a hasMetric property value.
     */
    boolean hasHasMetric();

    /**
     * Adds a hasMetric property value.<p>
     * 
     * @param newHasMetric the hasMetric property value to be added
     */
    void addHasMetric(WrappedIndividual newHasMetric);

    /**
     * Removes a hasMetric property value.<p>
     * 
     * @param oldHasMetric the hasMetric property value to be removed.
     */
    void removeHasMetric(WrappedIndividual oldHasMetric);


    /* ***************************************************
     * Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#ID
     */
     
    /**
     * Gets all property values for the ID property.<p>
     * 
     * @returns a collection of values for the ID property.
     */
    Collection<? extends String> getID();

    /**
     * Checks if the class has a ID property value.<p>
     * 
     * @return true if there is a ID property value.
     */
    boolean hasID();

    /**
     * Adds a ID property value.<p>
     * 
     * @param newID the ID property value to be added
     */
    void addID(String newID);

    /**
     * Removes a ID property value.<p>
     * 
     * @param oldID the ID property value to be removed.
     */
    void removeID(String oldID);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
