package com.thalesgroup.dtwc.protege;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: TWProblemDefinition <br>
 * @version generated on Wed Oct 08 11:02:03 CEST 2014 by t0013577
 */

public interface TWProblemDefinition extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#affectsAsset
     */
     
    /**
     * Gets all property values for the affectsAsset property.<p>
     * 
     * @returns a collection of values for the affectsAsset property.
     */
    Collection<? extends WrappedIndividual> getAffectsAsset();

    /**
     * Checks if the class has a affectsAsset property value.<p>
     * 
     * @return true if there is a affectsAsset property value.
     */
    boolean hasAffectsAsset();

    /**
     * Adds a affectsAsset property value.<p>
     * 
     * @param newAffectsAsset the affectsAsset property value to be added
     */
    void addAffectsAsset(WrappedIndividual newAffectsAsset);

    /**
     * Removes a affectsAsset property value.<p>
     * 
     * @param oldAffectsAsset the affectsAsset property value to be removed.
     */
    void removeAffectsAsset(WrappedIndividual oldAffectsAsset);


    /* ***************************************************
     * Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasThreat
     */
     
    /**
     * Gets all property values for the hasThreat property.<p>
     * 
     * @returns a collection of values for the hasThreat property.
     */
    Collection<? extends WrappedIndividual> getHasThreat();

    /**
     * Checks if the class has a hasThreat property value.<p>
     * 
     * @return true if there is a hasThreat property value.
     */
    boolean hasHasThreat();

    /**
     * Adds a hasThreat property value.<p>
     * 
     * @param newHasThreat the hasThreat property value to be added
     */
    void addHasThreat(WrappedIndividual newHasThreat);

    /**
     * Removes a hasThreat property value.<p>
     * 
     * @param oldHasThreat the hasThreat property value to be removed.
     */
    void removeHasThreat(WrappedIndividual oldHasThreat);


    /* ***************************************************
     * Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#ID
     */
     
    /**
     * Gets all property values for the ID property.<p>
     * 
     * @returns a collection of values for the ID property.
     */
    Collection<? extends String> getID();

    /**
     * Checks if the class has a ID property value.<p>
     * 
     * @return true if there is a ID property value.
     */
    boolean hasID();

    /**
     * Adds a ID property value.<p>
     * 
     * @param newID the ID property value to be added
     */
    void addID(String newID);

    /**
     * Removes a ID property value.<p>
     * 
     * @param oldID the ID property value to be removed.
     */
    void removeID(String oldID);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
