package com.thalesgroup.dtwc.protege;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: TWPropertySpecification <br>
 * @version generated on Wed Oct 08 11:02:03 CEST 2014 by t0013577
 */

public interface TWPropertySpecification extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasControl
     */
     
    /**
     * Gets all property values for the hasControl property.<p>
     * 
     * @returns a collection of values for the hasControl property.
     */
    Collection<? extends WrappedIndividual> getHasControl();

    /**
     * Checks if the class has a hasControl property value.<p>
     * 
     * @return true if there is a hasControl property value.
     */
    boolean hasHasControl();

    /**
     * Adds a hasControl property value.<p>
     * 
     * @param newHasControl the hasControl property value to be added
     */
    void addHasControl(WrappedIndividual newHasControl);

    /**
     * Removes a hasControl property value.<p>
     * 
     * @param oldHasControl the hasControl property value to be removed.
     */
    void removeHasControl(WrappedIndividual oldHasControl);


    /* ***************************************************
     * Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasTWProperty
     */
     
    /**
     * Gets all property values for the hasTWProperty property.<p>
     * 
     * @returns a collection of values for the hasTWProperty property.
     */
    Collection<? extends WrappedIndividual> getHasTWProperty();

    /**
     * Checks if the class has a hasTWProperty property value.<p>
     * 
     * @return true if there is a hasTWProperty property value.
     */
    boolean hasHasTWProperty();

    /**
     * Adds a hasTWProperty property value.<p>
     * 
     * @param newHasTWProperty the hasTWProperty property value to be added
     */
    void addHasTWProperty(WrappedIndividual newHasTWProperty);

    /**
     * Removes a hasTWProperty property value.<p>
     * 
     * @param oldHasTWProperty the hasTWProperty property value to be removed.
     */
    void removeHasTWProperty(WrappedIndividual oldHasTWProperty);


    /* ***************************************************
     * Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#ID
     */
     
    /**
     * Gets all property values for the ID property.<p>
     * 
     * @returns a collection of values for the ID property.
     */
    Collection<? extends String> getID();

    /**
     * Checks if the class has a ID property value.<p>
     * 
     * @return true if there is a ID property value.
     */
    boolean hasID();

    /**
     * Adds a ID property value.<p>
     * 
     * @param newID the ID property value to be added
     */
    void addID(String newID);

    /**
     * Removes a ID property value.<p>
     * 
     * @param oldID the ID property value to be removed.
     */
    void removeID(String oldID);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
