package com.thalesgroup.dtwc.protege;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: TWProperty <br>
 * @version generated on Wed Oct 08 11:02:03 CEST 2014 by t0013577
 */

public interface TWProperty extends WrappedIndividual {

    /* ***************************************************
     * Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasAsset
     */
     
    /**
     * Gets all property values for the hasAsset property.<p>
     * 
     * @returns a collection of values for the hasAsset property.
     */
    Collection<? extends WrappedIndividual> getHasAsset();

    /**
     * Checks if the class has a hasAsset property value.<p>
     * 
     * @return true if there is a hasAsset property value.
     */
    boolean hasHasAsset();

    /**
     * Adds a hasAsset property value.<p>
     * 
     * @param newHasAsset the hasAsset property value to be added
     */
    void addHasAsset(WrappedIndividual newHasAsset);

    /**
     * Removes a hasAsset property value.<p>
     * 
     * @param oldHasAsset the hasAsset property value to be removed.
     */
    void removeHasAsset(WrappedIndividual oldHasAsset);


    /* ***************************************************
     * Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasContext
     */
     
    /**
     * Gets all property values for the hasContext property.<p>
     * 
     * @returns a collection of values for the hasContext property.
     */
    Collection<? extends WrappedIndividual> getHasContext();

    /**
     * Checks if the class has a hasContext property value.<p>
     * 
     * @return true if there is a hasContext property value.
     */
    boolean hasHasContext();

    /**
     * Adds a hasContext property value.<p>
     * 
     * @param newHasContext the hasContext property value to be added
     */
    void addHasContext(WrappedIndividual newHasContext);

    /**
     * Removes a hasContext property value.<p>
     * 
     * @param oldHasContext the hasContext property value to be removed.
     */
    void removeHasContext(WrappedIndividual oldHasContext);


    /* ***************************************************
     * Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasTWAttribute
     */
     
    /**
     * Gets all property values for the hasTWAttribute property.<p>
     * 
     * @returns a collection of values for the hasTWAttribute property.
     */
    Collection<? extends WrappedIndividual> getHasTWAttribute();

    /**
     * Checks if the class has a hasTWAttribute property value.<p>
     * 
     * @return true if there is a hasTWAttribute property value.
     */
    boolean hasHasTWAttribute();

    /**
     * Adds a hasTWAttribute property value.<p>
     * 
     * @param newHasTWAttribute the hasTWAttribute property value to be added
     */
    void addHasTWAttribute(WrappedIndividual newHasTWAttribute);

    /**
     * Removes a hasTWAttribute property value.<p>
     * 
     * @param oldHasTWAttribute the hasTWAttribute property value to be removed.
     */
    void removeHasTWAttribute(WrappedIndividual oldHasTWAttribute);


    /* ***************************************************
     * Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#ID
     */
     
    /**
     * Gets all property values for the ID property.<p>
     * 
     * @returns a collection of values for the ID property.
     */
    Collection<? extends String> getID();

    /**
     * Checks if the class has a ID property value.<p>
     * 
     * @return true if there is a ID property value.
     */
    boolean hasID();

    /**
     * Adds a ID property value.<p>
     * 
     * @param newID the ID property value to be added
     */
    void addID(String newID);

    /**
     * Removes a ID property value.<p>
     * 
     * @param oldID the ID property value to be removed.
     */
    void removeID(String oldID);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
