package com.thalesgroup.dtwc.protege;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Wed Oct 08 11:02:03 CEST 2014 by t0013577
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.optet.eu/ns/DigitalTrustworthinessCertificate#Asset
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ASSET.<p>
     * 
     */
    public static final OWLClass CLASS_ASSET = factory.getOWLClass(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#Asset"));

    /* ***************************************************
     * Class http://www.optet.eu/ns/DigitalTrustworthinessCertificate#Attribute
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ATTRIBUTE.<p>
     * 
     */
    public static final OWLClass CLASS_ATTRIBUTE = factory.getOWLClass(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#Attribute"));

    /* ***************************************************
     * Class http://www.optet.eu/ns/DigitalTrustworthinessCertificate#Behaviour
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BEHAVIOUR.<p>
     * 
     */
    public static final OWLClass CLASS_BEHAVIOUR = factory.getOWLClass(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#Behaviour"));

    /* ***************************************************
     * Class http://www.optet.eu/ns/DigitalTrustworthinessCertificate#CertifiedEvidence
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CERTIFIEDEVIDENCE.<p>
     * 
     */
    public static final OWLClass CLASS_CERTIFIEDEVIDENCE = factory.getOWLClass(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#CertifiedEvidence"));

    /* ***************************************************
     * Class http://www.optet.eu/ns/DigitalTrustworthinessCertificate#Component
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMPONENT.<p>
     * 
     */
    public static final OWLClass CLASS_COMPONENT = factory.getOWLClass(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#Component"));

    /* ***************************************************
     * Class http://www.optet.eu/ns/DigitalTrustworthinessCertificate#ComponentModel
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMPONENTMODEL.<p>
     * 
     */
    public static final OWLClass CLASS_COMPONENTMODEL = factory.getOWLClass(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#ComponentModel"));

    /* ***************************************************
     * Class http://www.optet.eu/ns/DigitalTrustworthinessCertificate#Context
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTEXT.<p>
     * 
     */
    public static final OWLClass CLASS_CONTEXT = factory.getOWLClass(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#Context"));

    /* ***************************************************
     * Class http://www.optet.eu/ns/DigitalTrustworthinessCertificate#Control
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONTROL.<p>
     * 
     */
    public static final OWLClass CLASS_CONTROL = factory.getOWLClass(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#Control"));

    /* ***************************************************
     * Class http://www.optet.eu/ns/DigitalTrustworthinessCertificate#DTWC
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DTWC.<p>
     * 
     */
    public static final OWLClass CLASS_DTWC = factory.getOWLClass(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#DTWC"));

    /* ***************************************************
     * Class http://www.optet.eu/ns/DigitalTrustworthinessCertificate#Evidence
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EVIDENCE.<p>
     * 
     */
    public static final OWLClass CLASS_EVIDENCE = factory.getOWLClass(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#Evidence"));

    /* ***************************************************
     * Class http://www.optet.eu/ns/DigitalTrustworthinessCertificate#Metric
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class METRIC.<p>
     * 
     */
    public static final OWLClass CLASS_METRIC = factory.getOWLClass(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#Metric"));

    /* ***************************************************
     * Class http://www.optet.eu/ns/DigitalTrustworthinessCertificate#MetricRuntimeCalculation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class METRICRUNTIMECALCULATION.<p>
     * 
     */
    public static final OWLClass CLASS_METRICRUNTIMECALCULATION = factory.getOWLClass(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#MetricRuntimeCalculation"));

    /* ***************************************************
     * Class http://www.optet.eu/ns/DigitalTrustworthinessCertificate#RuntimeEvidence
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RUNTIMEEVIDENCE.<p>
     * 
     */
    public static final OWLClass CLASS_RUNTIMEEVIDENCE = factory.getOWLClass(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#RuntimeEvidence"));

    /* ***************************************************
     * Class http://www.optet.eu/ns/DigitalTrustworthinessCertificate#Stakeholder
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class STAKEHOLDER.<p>
     * 
     */
    public static final OWLClass CLASS_STAKEHOLDER = factory.getOWLClass(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#Stakeholder"));

    /* ***************************************************
     * Class http://www.optet.eu/ns/DigitalTrustworthinessCertificate#SubComponent
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SUBCOMPONENT.<p>
     * 
     */
    public static final OWLClass CLASS_SUBCOMPONENT = factory.getOWLClass(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#SubComponent"));

    /* ***************************************************
     * Class http://www.optet.eu/ns/DigitalTrustworthinessCertificate#SystemDescription
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SYSTEMDESCRIPTION.<p>
     * 
     */
    public static final OWLClass CLASS_SYSTEMDESCRIPTION = factory.getOWLClass(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#SystemDescription"));

    /* ***************************************************
     * Class http://www.optet.eu/ns/DigitalTrustworthinessCertificate#TWAttribute
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TWATTRIBUTE.<p>
     * 
     */
    public static final OWLClass CLASS_TWATTRIBUTE = factory.getOWLClass(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#TWAttribute"));

    /* ***************************************************
     * Class http://www.optet.eu/ns/DigitalTrustworthinessCertificate#TWProblemDefinition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TWPROBLEMDEFINITION.<p>
     * 
     */
    public static final OWLClass CLASS_TWPROBLEMDEFINITION = factory.getOWLClass(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#TWProblemDefinition"));

    /* ***************************************************
     * Class http://www.optet.eu/ns/DigitalTrustworthinessCertificate#TWProperty
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TWPROPERTY.<p>
     * 
     */
    public static final OWLClass CLASS_TWPROPERTY = factory.getOWLClass(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#TWProperty"));

    /* ***************************************************
     * Class http://www.optet.eu/ns/DigitalTrustworthinessCertificate#TWPropertySpecification
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TWPROPERTYSPECIFICATION.<p>
     * 
     */
    public static final OWLClass CLASS_TWPROPERTYSPECIFICATION = factory.getOWLClass(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#TWPropertySpecification"));

    /* ***************************************************
     * Class http://www.optet.eu/ns/DigitalTrustworthinessCertificate#Threat
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class THREAT.<p>
     * 
     */
    public static final OWLClass CLASS_THREAT = factory.getOWLClass(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#Threat"));

    /* ***************************************************
     * Class http://xmlns.com/foaf/0.1/Person
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERSON.<p>
     * 
     */
    public static final OWLClass CLASS_PERSON = factory.getOWLClass(IRI.create("http://xmlns.com/foaf/0.1/Person"));

    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#affectsAsset
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property AFFECTSASSET.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_AFFECTSASSET = factory.getOWLObjectProperty(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#affectsAsset"));

    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasAsset
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASASSET.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASASSET = factory.getOWLObjectProperty(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasAsset"));

    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasAssociatedStakeholder
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASASSOCIATEDSTAKEHOLDER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASASSOCIATEDSTAKEHOLDER = factory.getOWLObjectProperty(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasAssociatedStakeholder"));

    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasBehaviour
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASBEHAVIOUR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASBEHAVIOUR = factory.getOWLObjectProperty(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasBehaviour"));

    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasContext
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONTEXT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONTEXT = factory.getOWLObjectProperty(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasContext"));

    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasControl
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONTROL.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONTROL = factory.getOWLObjectProperty(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasControl"));

    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasEvidence
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASEVIDENCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASEVIDENCE = factory.getOWLObjectProperty(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasEvidence"));

    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasMetric
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASMETRIC.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASMETRIC = factory.getOWLObjectProperty(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasMetric"));

    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasMetricCalculationMethod
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASMETRICCALCULATIONMETHOD.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASMETRICCALCULATIONMETHOD = factory.getOWLObjectProperty(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasMetricCalculationMethod"));

    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasPart
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASPART.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASPART = factory.getOWLObjectProperty(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasPart"));

    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasStakeholder
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSTAKEHOLDER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSTAKEHOLDER = factory.getOWLObjectProperty(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasStakeholder"));

    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasSubComponent
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSUBCOMPONENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSUBCOMPONENT = factory.getOWLObjectProperty(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasSubComponent"));

    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasTWAttribute
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASTWATTRIBUTE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASTWATTRIBUTE = factory.getOWLObjectProperty(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasTWAttribute"));

    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasTWProblemDefinition
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASTWPROBLEMDEFINITION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASTWPROBLEMDEFINITION = factory.getOWLObjectProperty(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasTWProblemDefinition"));

    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasTWProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASTWPROPERTY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASTWPROPERTY = factory.getOWLObjectProperty(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasTWProperty"));

    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasTWPropertySpecification
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASTWPROPERTYSPECIFICATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASTWPROPERTYSPECIFICATION = factory.getOWLObjectProperty(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasTWPropertySpecification"));

    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasThreat
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASTHREAT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASTHREAT = factory.getOWLObjectProperty(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasThreat"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#topObjectProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property TOPOBJECTPROPERTY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_TOPOBJECTPROPERTY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#topObjectProperty"));

    /* ***************************************************
     * Data Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#ID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ID = factory.getOWLDataProperty(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#ID"));

    /* ***************************************************
     * Data Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasHash
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASHASH.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASHASH = factory.getOWLDataProperty(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasHash"));

    /* ***************************************************
     * Data Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasUnit
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASUNIT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASUNIT = factory.getOWLDataProperty(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasUnit"));

    /* ***************************************************
     * Data Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASVALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASVALUE = factory.getOWLDataProperty(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasValue"));

    /* ***************************************************
     * Data Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#inTargetOfEvaluation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property INTARGETOFEVALUATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_INTARGETOFEVALUATION = factory.getOWLDataProperty(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#inTargetOfEvaluation"));

    /* ***************************************************
     * Data Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#type
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TYPE = factory.getOWLDataProperty(IRI.create("http://www.optet.eu/ns/DigitalTrustworthinessCertificate#type"));

    /* ***************************************************
     * Data Property http://www.w3.org/2002/07/owl#topDataProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TOPDATAPROPERTY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TOPDATAPROPERTY = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2002/07/owl#topDataProperty"));


}
