package com.thalesgroup.dtwc.protege.impl;

import com.thalesgroup.dtwc.protege.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultDTWC <br>
 * @version generated on Wed Oct 08 11:02:03 CEST 2014 by t0013577
 */
public class DefaultDTWC extends WrappedIndividualImpl implements DTWC {

    public DefaultDTWC(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasEvidence
     */
     
    public Collection<? extends WrappedIndividual> getHasEvidence() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASEVIDENCE,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasHasEvidence() {
	   return !getHasEvidence().isEmpty();
    }

    public void addHasEvidence(WrappedIndividual newHasEvidence) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASEVIDENCE,
                                       newHasEvidence);
    }

    public void removeHasEvidence(WrappedIndividual oldHasEvidence) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASEVIDENCE,
                                          oldHasEvidence);
    }


    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasPart
     */
     
    public Collection<? extends WrappedIndividual> getHasPart() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASPART,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasHasPart() {
	   return !getHasPart().isEmpty();
    }

    public void addHasPart(WrappedIndividual newHasPart) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASPART,
                                       newHasPart);
    }

    public void removeHasPart(WrappedIndividual oldHasPart) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASPART,
                                          oldHasPart);
    }


    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasTWProblemDefinition
     */
     
    public Collection<? extends WrappedIndividual> getHasTWProblemDefinition() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASTWPROBLEMDEFINITION,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasHasTWProblemDefinition() {
	   return !getHasTWProblemDefinition().isEmpty();
    }

    public void addHasTWProblemDefinition(WrappedIndividual newHasTWProblemDefinition) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASTWPROBLEMDEFINITION,
                                       newHasTWProblemDefinition);
    }

    public void removeHasTWProblemDefinition(WrappedIndividual oldHasTWProblemDefinition) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASTWPROBLEMDEFINITION,
                                          oldHasTWProblemDefinition);
    }


    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasTWPropertySpecification
     */
     
    public Collection<? extends WrappedIndividual> getHasTWPropertySpecification() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASTWPROPERTYSPECIFICATION,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasHasTWPropertySpecification() {
	   return !getHasTWPropertySpecification().isEmpty();
    }

    public void addHasTWPropertySpecification(WrappedIndividual newHasTWPropertySpecification) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASTWPROPERTYSPECIFICATION,
                                       newHasTWPropertySpecification);
    }

    public void removeHasTWPropertySpecification(WrappedIndividual oldHasTWPropertySpecification) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASTWPROPERTYSPECIFICATION,
                                          oldHasTWPropertySpecification);
    }


    /* ***************************************************
     * Data Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#ID
     */
     
    public Collection<? extends String> getID() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ID, String.class);
    }

    public boolean hasID() {
		return !getID().isEmpty();
    }

    public void addID(String newID) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ID, newID);
    }

    public void removeID(String oldID) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ID, oldID);
    }


    /* ***************************************************
     * Data Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasHash
     */
     
    public Collection<? extends Object> getHasHash() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASHASH, Object.class);
    }

    public boolean hasHasHash() {
		return !getHasHash().isEmpty();
    }

    public void addHasHash(Object newHasHash) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASHASH, newHasHash);
    }

    public void removeHasHash(Object oldHasHash) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASHASH, oldHasHash);
    }


}
