package com.thalesgroup.dtwc.protege.impl;

import com.thalesgroup.dtwc.protege.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultTWProperty <br>
 * @version generated on Wed Oct 08 11:02:03 CEST 2014 by t0013577
 */
public class DefaultTWProperty extends WrappedIndividualImpl implements TWProperty {

    public DefaultTWProperty(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasAsset
     */
     
    public Collection<? extends WrappedIndividual> getHasAsset() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASASSET,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasHasAsset() {
	   return !getHasAsset().isEmpty();
    }

    public void addHasAsset(WrappedIndividual newHasAsset) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASASSET,
                                       newHasAsset);
    }

    public void removeHasAsset(WrappedIndividual oldHasAsset) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASASSET,
                                          oldHasAsset);
    }


    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasContext
     */
     
    public Collection<? extends WrappedIndividual> getHasContext() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASCONTEXT,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasHasContext() {
	   return !getHasContext().isEmpty();
    }

    public void addHasContext(WrappedIndividual newHasContext) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASCONTEXT,
                                       newHasContext);
    }

    public void removeHasContext(WrappedIndividual oldHasContext) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASCONTEXT,
                                          oldHasContext);
    }


    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasTWAttribute
     */
     
    public Collection<? extends WrappedIndividual> getHasTWAttribute() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASTWATTRIBUTE,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasHasTWAttribute() {
	   return !getHasTWAttribute().isEmpty();
    }

    public void addHasTWAttribute(WrappedIndividual newHasTWAttribute) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASTWATTRIBUTE,
                                       newHasTWAttribute);
    }

    public void removeHasTWAttribute(WrappedIndividual oldHasTWAttribute) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASTWATTRIBUTE,
                                          oldHasTWAttribute);
    }


    /* ***************************************************
     * Data Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#ID
     */
     
    public Collection<? extends String> getID() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ID, String.class);
    }

    public boolean hasID() {
		return !getID().isEmpty();
    }

    public void addID(String newID) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ID, newID);
    }

    public void removeID(String oldID) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ID, oldID);
    }


}
