package com.thalesgroup.dtwc.protege.impl;

import com.thalesgroup.dtwc.protege.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultComponent <br>
 * @version generated on Wed Oct 08 11:02:03 CEST 2014 by t0013577
 */
public class DefaultComponent extends WrappedIndividualImpl implements Component {

    public DefaultComponent(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasAssociatedStakeholder
     */
     
    public Collection<? extends WrappedIndividual> getHasAssociatedStakeholder() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASASSOCIATEDSTAKEHOLDER,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasHasAssociatedStakeholder() {
	   return !getHasAssociatedStakeholder().isEmpty();
    }

    public void addHasAssociatedStakeholder(WrappedIndividual newHasAssociatedStakeholder) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASASSOCIATEDSTAKEHOLDER,
                                       newHasAssociatedStakeholder);
    }

    public void removeHasAssociatedStakeholder(WrappedIndividual oldHasAssociatedStakeholder) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASASSOCIATEDSTAKEHOLDER,
                                          oldHasAssociatedStakeholder);
    }


    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasBehaviour
     */
     
    public Collection<? extends WrappedIndividual> getHasBehaviour() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASBEHAVIOUR,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasHasBehaviour() {
	   return !getHasBehaviour().isEmpty();
    }

    public void addHasBehaviour(WrappedIndividual newHasBehaviour) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASBEHAVIOUR,
                                       newHasBehaviour);
    }

    public void removeHasBehaviour(WrappedIndividual oldHasBehaviour) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASBEHAVIOUR,
                                          oldHasBehaviour);
    }


    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasPart
     */
     
    public Collection<? extends WrappedIndividual> getHasPart() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASPART,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasHasPart() {
	   return !getHasPart().isEmpty();
    }

    public void addHasPart(WrappedIndividual newHasPart) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASPART,
                                       newHasPart);
    }

    public void removeHasPart(WrappedIndividual oldHasPart) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASPART,
                                          oldHasPart);
    }


    /* ***************************************************
     * Data Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#ID
     */
     
    public Collection<? extends String> getID() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ID, String.class);
    }

    public boolean hasID() {
		return !getID().isEmpty();
    }

    public void addID(String newID) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ID, newID);
    }

    public void removeID(String oldID) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ID, oldID);
    }


    /* ***************************************************
     * Data Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#inTargetOfEvaluation
     */
     
    public Collection<? extends Boolean> getInTargetOfEvaluation() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INTARGETOFEVALUATION, Boolean.class);
    }

    public boolean hasInTargetOfEvaluation() {
		return !getInTargetOfEvaluation().isEmpty();
    }

    public void addInTargetOfEvaluation(Boolean newInTargetOfEvaluation) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INTARGETOFEVALUATION, newInTargetOfEvaluation);
    }

    public void removeInTargetOfEvaluation(Boolean oldInTargetOfEvaluation) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_INTARGETOFEVALUATION, oldInTargetOfEvaluation);
    }


    /* ***************************************************
     * Data Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#type
     */
     
    public Collection<? extends String> getType() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TYPE, String.class);
    }

    public boolean hasType() {
		return !getType().isEmpty();
    }

    public void addType(String newType) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TYPE, newType);
    }

    public void removeType(String oldType) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TYPE, oldType);
    }


}
