package com.thalesgroup.dtwc.protege.impl;

import com.thalesgroup.dtwc.protege.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultTWProblemDefinition <br>
 * @version generated on Wed Oct 08 11:02:03 CEST 2014 by t0013577
 */
public class DefaultTWProblemDefinition extends WrappedIndividualImpl implements TWProblemDefinition {

    public DefaultTWProblemDefinition(OWLOntology ontology, IRI iri) {
        super(ontology, iri);
    }





    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#affectsAsset
     */
     
    public Collection<? extends WrappedIndividual> getAffectsAsset() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_AFFECTSASSET,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasAffectsAsset() {
	   return !getAffectsAsset().isEmpty();
    }

    public void addAffectsAsset(WrappedIndividual newAffectsAsset) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_AFFECTSASSET,
                                       newAffectsAsset);
    }

    public void removeAffectsAsset(WrappedIndividual oldAffectsAsset) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_AFFECTSASSET,
                                          oldAffectsAsset);
    }


    /* ***************************************************
     * Object Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#hasThreat
     */
     
    public Collection<? extends WrappedIndividual> getHasThreat() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASTHREAT,
                                               WrappedIndividualImpl.class);
    }

    public boolean hasHasThreat() {
	   return !getHasThreat().isEmpty();
    }

    public void addHasThreat(WrappedIndividual newHasThreat) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASTHREAT,
                                       newHasThreat);
    }

    public void removeHasThreat(WrappedIndividual oldHasThreat) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASTHREAT,
                                          oldHasThreat);
    }


    /* ***************************************************
     * Data Property http://www.optet.eu/ns/DigitalTrustworthinessCertificate#ID
     */
     
    public Collection<? extends String> getID() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ID, String.class);
    }

    public boolean hasID() {
		return !getID().isEmpty();
    }

    public void addID(String newID) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ID, newID);
    }

    public void removeID(String oldID) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_ID, oldID);
    }


}
